fname = [
"Miguel",
"Arthur",
"Bernardo",
"Heitor",
"Davi",
"Lorenzo",
"Theo",
"Pedro",
"Gabriel",
"Enzo",
"Matheus",
"Lucas",
"Benjamin",
"Nicolas",
"Guilherme",
"Rafael",
"Joaquim",
"Samuel",
"Enzo",
"Joao",
"Henrique",
"Gustavo",
"Murilo",
"Pedro",
"Pietro",
"Lucca",
"Felipe",
"Joao",
"Isaac",
"Benicio",
"Daniel",
"Anthony",
"Leonardo",
"DaviLucca",
"Bryan",
"Eduardo",
"Joao",
"Victor",
"Joao",
"Caua",
"Antonio",
"Vicente",
"Caleb",
"Gael",
"Bento",
"Caio",
"Emanuel",
"Vinicius",
"Joao",
"Davi",
"Noah",
"Joao",
"Luiz",
"Francisco",
"Kaique",
"Otavio",
"Augusto",
"Levi",
"Yuri",
"Enrico",
"Thiago",
"Ian",
"Victor",
"Thomas",
"Henry",
"Felipe",
"Ryan",
"Miguel",
"Luiz",
"Nathan",
"Lucas",
"Miguel",
"Raul",
"Miguel",
"Henrique",
"Luan",
"Erick",
"Martin",
"Bruno",
"Rodrigo",
"Gustavo",
"Breno",
"Kaue",
"Fernando",
"Tomas",
"Andre",
"Jose",
"Yago",
"Danilo",
"Ruan",
"Oliver",
"Alice",
"Sophia",
"Helena",
"Valentina",
"Laura",
"Isabella",
"Manuela",
"Julia",
"Heloisa",
"Luiza",
"Lorena",
"Livia",
"Giovanna",
"Beatriz",
"Cecilia",
"Eloa",
"Lara",
"Isadora",
"Mariana",
"Emanuelly",
"Ana",
"Melissa",
"Yasmin",
"Isabelly",
"Lavinia",
"Esther",
"Sarah",
"Elisa",
"Antonella",
"Rafaela",
"Liz",
"Marina",
"Nicole",
"Maite",
"Isis",
"Alicia",
"Luna",
"Rebeca",
"Agatha",
"Leticia",
"Maria-",
"Gabriela",
"Catarina",
"Clara",
"Vitoria",
"Olivia",
"Emilly",
"Milena",
"Bianca",
"Larissa",
"Mirella",
"Allana",
"Clarice",
"Pietra",
"Maya",
"Lais",
"Ayla",
"Eduarda",
"Mariah",
"Stella",
"Ana",
"Gabrielly",
"Sophie",
"Carolina",
"Fernanda",
"Malu",
"Analu",
"Amanda",
"Aurora",
"Louise",
"Heloise",
"Joana",
"Luana",
"Antonia",
"Isabel",
"Bruna"
]

lname = [
"Muniz",
"Schumacher",
"Mazzaropi",
"Monteiro",
"Muller",
"Marques",
"Moraes",
"Duarte",
"Vasconcelos",
"Montenegro",
"Fagundes",
"Trindade",
"Vargas",
"Ferraz",
"Carvalho",
"Dolabella",
"Evelyn",
"Reymond",
"Lins",
"Andrade",
"Boaventura",
"Barcellos",
"Dantas",
"Oliveira",
"Carvalho",
"Vilela",
"Santana",
"Ribeiro",
"Barros",
"Moscovis",
"Goncalves",
"Johnson",
"Castro",
"Assuncao",
"Kannenberg",
"Torres",
"Gomes",
"Alves",
"Steves",
"Garcia",
"Moura",
"Albuquerque",
"Antunes",
"Barcelos",
"Roriz",
"Ferrari",
"Castiel",
"Fischer",
"Novaes",
"Gimenez",
"Schoemberger",
"Falabella",
"Martins",
"Drummond",
"Figueiredo",
"Resende",
"Sampaio",
"Fernandes",
"Cavalcante",
"Arantes",
"Lombardi",
"Dieckmann",
"Goes",
"Menezes",
"Ganzarolli",
"Guimaraes",
"Liberato",
"Alencar",
"Marinho",
"Lambertini",
"Lafaiete",
"Sanches",
"Timberg",
"Bernardi",
"Werneck",
"Schmutz",
"Annenberg",
"Campos",
"Medeiros",
"Lessa",
"Hickmann",
"ontenelle",
"Bittencourt",
"Noronha",
"Abravanel",
"Sheherazade",
"Bastos",
"Meneghel",
"Bonner",
"Riche",
"Chapelin",
"Rios",
"Giacomo",
"Davila",
"Close",
"Bial",
"Maldonado",
"Bongiovanni",
"Vitti",
"Silverstone"
]

domain = ["@gmail.com", "@terra.com", "@live.com", "@hotmail.com", "@yahoo.com.br", "@bol.com.br", "@msn.com", "@ig.com.br"]

endereco = [
"Av.  Manoel Jose Pereira, 332",
"Rua Januario P. Trannim, 45",
"Rua Jose Bencz, 232",
"Rua Joao Batista de Siqueira 13",
"Av. Jaime Canet s/n ",
"Av. Pedro Amaro dos Santos 1407",
"Av. das Americas, 2016",
"Rua Sebastiao Pereira Oliveira 1700",
"Rua Natal Bufalo de Moraes, 233",
"Rua XV de Novembro 58",
"Rua Presidente Kennedy, 1515",
"Av. Brasil,  01",
"Rua Curitiba, nº 250",
"Av. Valerio O. Estevao, 83",
"Rua Cel. Marcalo, 164",
"Rua Matias Ap. Fogaca, 215",
"Rua Luiz Picolli, 299",
"Avenida Italo Orcelli nº 601",
"Rua Jose Cunha Neto, 190",
"Rua Jose Frediani, 213 ",
"Rua Joao XXIII, 127",
"Rua Argentina, 95",
"Rua Vereador Homero Franco,435",
"Travessa Presidente Vargas, S/N",
"Av. Prof. Joao Cândido 115",
"Rua Dezoito, N 101",
"Rua Andre Valenga, 308",
"Rua Rodolfo Castagnoli, 200",
"Rua Silvestre Jarek, 155 Sala 2",
"Av.  Joao Bento, 1899",
"Av.  Parana S/N",
"Av. XV de Novembro, 1761",
"Rua Cinderela S/N",
"Rua Bahia,888",
"Av.  Iguacu, N 430",
"Rua Ouro Branco, 238     ",
"Rua Salvira Marques, 264",
"Av. Brasil, 2040 Cx. 333",
"Rua Padre Damaso, 46        ",
"Rua 25 De Julho, 529",
"Rua Bruno Polleto, 31         ",
"Rua Barao do Cerro Azul 65",
"Rua Mal Cândido Rondon, 368",
"Rua 14 de Dezembro, 4935",
"Av.  Santa Catarina, 651",
"Rua Mestrinho, 40",
"Av.  Prof. Joao B. Lovato 360",
"Av.  Brasil, 95",
"Rua Frei Demetrio, 77",
"Rua Dona Celina, 236",
"Rua Joao Franco 402",
"Rua Flor de Lis, 2066 ",
"Travessa Diogo C. Parra, 74",
"Rua Jose Salvador S/N",
"Rua Sete de Setembro 62",
"Rua Tocantins, 151",
"Av. Pres. Getulio Vargas, 492",
"Av.  Treze de Maio, 753",
"Av.  Brasil, 3054           ",
"Rua Santos Dumont 470",
"Av. Pe. Gualter Farias Negrao S/N",
"Rua da Bandeira, 500",
"Rua Jose Manoel Batista, 241",
"Rua Reynaldo Massi, S/N",
"Av.  Brasil, 344",
"Avenida Ivan Ferreira do Amaral, s/n",
"Rua Rio Grande do Sul, 924",
"Rua Parana, 4810",
"Rua da Constelacao, 466",
"Av. Sao Joao Batista , s/n"
]

presidentes = [
"Alvaro Dias",
"Ciro Gomes",
"Marina Silva",
"Geraldo Alckmin",
"Jair Bolsonaro","Jair Bolsonaro","Jair Bolsonaro",
"Fernando Haddad",
"Henrique Meirelles",
"Joao Amoedo",
"Guilherme Boulos",
"Jose Maria Eymael",
"Cabo Daciolo",
"Joao Goulart Filho",
"Vera Lucia",
"Brancos e nulos"
]


